### PR TITLE
Added `get_sha` method and use it when releasing a reference

### PR DESCRIPTION
**Pull request by jkimbo**
Came across this issue when trying to release a branch and freight was just releasing the most recent tagged commit in the repository. Not very familiar with the inner workings of git but using `show-ref` instead of `describe` seems like a better way of getting the correct reference of what to deploy?

### CODE REVIEW

**Comment by jkimbo** [comment]
Not quite sure why the tests are failing for this?

**Comment by dcramer** [comment]
Ignore Travis -- we need to change how tests work for them to function there atm

**Comment by dcramer** [comment]
I'm not sure how I ignored this one before. I need to figure out if this is correct, but I'm not clear why we wouldn't have this problem.

We run "deploy master" frequently and its never not been the latest sha of ref

**Comment by jkimbo** [comment]
So I came across this problem when trying to deploy a branch and it instead picked up one of our release tags (not even the most recent one oddly). I thought it might have to do with `git-describe` only looking for annotated tags? We use github to create all our tags through releases so I don't know what tags they actually create. Again not that familiar with the inner workings of git so I could be completely barking up the wrong tree!

**Comment by dcramer** [comment]
Was the branch name the same as the tag? (can you even do that??)

**Comment by jkimbo** [comment]
No, different names (although it does appear you can have a branch be the same name as tag)

**Comment by jkimbo** [comment]
bump @dcramer ?

**Comment by dcramer** [comment]
Sorry, never ending queue of email has me constantly losing track :)

**Comment by jkimbo** [comment]
Thanks!

**Pull request merged**
