### PR TITLE
Fix config docker-compose

### PR DESCRIPTION
**Pull request by NamPNQ**
Fix not connect to db and redis

### CODE REVIEW

**Comment by dcramer** [comment]
Thanks!

**Comment by marksteve** [comment]
@NamPNQ I put those values inside the `.env` file in case you need to add passwords or a different host.

**Comment by NamPNQ** [comment]
I think `.env` is good case for some other config like as GOOGLEC_CLIENT_ID, GOOGLE_CLIENT_SECRET :D

**Comment by marksteve** [comment]
@NamPNQ Yep but you wouldn't want your db passwords in code or force users to use a docker container for their dbs. It's easy to put in those config values in the `.env`. @dcramer thoughts?

**Comment by dcramer** [comment]
It's not clear to me what the goals are with compose. How would you use it in a production env? (I know nothing about the Docker ecosystem)

I will say it is reasonably easy to add things to .env, but if at the same time we're intending the Docker setup to simple then this seems ok. With that said, if it's not reasonable to override those settings, it does seem like this would make it more limited.

**Comment by marksteve** [comment]
I guess the question now is "For which kind of docker users the project is catering to? Prod or not?". If the answer is it's just for users that only use docker for dev then I'm good with this change. But freight is meant to be used in production. So I think it should be more prod friendly.

**Comment by dcramer** [comment]
@marksteve so my main question would be "does this at all affect overwriting the settings with .env" (or similar). If it doesn't then I think this is safe. If it does, then you're right, and we probably shouldn't do this as a default.

**Comment by marksteve** [comment]
Just did a quick test and it does: https://gist.github.com/marksteve/c59351821d666dabb645

**Comment by dcramer** [comment]
I've gone ahead and reverted a11697e

**Pull request merged**
