### PR TITLE
feat(pipeline): Pass environment configuration to the steps via PipelineContext

### PR DESCRIPTION
**Pull request by beezz**

### CODE REVIEW

**Comment by beezz** [comment]
This is extending the `PipelineContext` with environment coming from app configuration. It's not the deploy model where environment is a string.

**Comment by mattrobenolt** [comment]
I'm skeptical based on this code:

image

Since `deploy.environment` is a string.

What's the example JSON/yaml config you'd expect to make this work? Maybe I'm missing the full picture.

**Comment by mattrobenolt** [comment]
Oh, I think I see what you're talking about. It's coming from here: https://github.com/getsentry/freight/blob/master/freight/models/app.py#L36-L38

**Comment by mattrobenolt** [comment]
Ok, so in that case, why not change the name to simply `instances` instead of `num_of_canary_instances` since there's no other real application, and decouple the name of "canary" since that doesn't really matter here. You're just defining how many instances are a part of this group.

The only _slight_ concern is that we'll have to remember that this _only_ applies to a statefulset and since this is configured at the app level, it's not obvious. Maybe if the name were like, `statefulset_instances` ? Just to be explicit, since this wouldn't work or apply to a Deployment for example, or anything outside of the pipeline provider.

**Comment by beezz** [comment]
I like the `statefulset_instances`, indeed makes the intention clearer.

**Pull request merged**
