### PR TITLE
Get db uri and broker url config from env vars

### PR DESCRIPTION
**Pull request by marksteve**

### CODE REVIEW

**Comment by dcramer** [comment]
What issues were you seeing? We're using this flask-heroku thing which actually does a bunch of this kind of stuff

**Comment by marksteve** [comment]
@dcramer So it should've taken values from env? I tried running `bin/upgrade` but it was using the defaults when I checked `db.engine`

**Comment by marksteve** [comment]
@dcramer I'll investigate what's happening in my setup. At least TIL about Flask-Heroku :)

**Comment by marksteve** [comment]
Ah okay. Should've set `DATABASE_URL` and `REDISCLOUD_URL`.

**Comment by dcramer** [comment]
On that note, if you want to re-open this I'll definitely merge it. I dont want anything to be locked into Heroku, I just for some reason was assuming it was using the generic values.

**Comment by dcramer** [comment]
jk found I can re-open it :)

**Pull request merged**
