### PR TITLE
Don't use last tag for deploy

### PR DESCRIPTION
**Pull request by NamPNQ**

### CODE REVIEW

**Comment by dcramer** [comment]
Can you explain what your goal is?

We explicitly pin to the sha when initiaiting the deploy (rather than the ref) because the checks rely on the sha. The ref is really only available so you have some kind of idea of what initiated the deploy.

**Comment by NamPNQ** [comment]
I found in code, you get hash of lastest tag and set it to sha [default](https://github.com/getsentry/freight/blob/master/freight/api/task_index.py#L104)

**Comment by dcramer** [comment]
@NamPNQ thats correct. When the build is created we determine the sha explicitly.

I'm closing this but feel free to reopen if you have more information on why you think this change is valuable.

**Comment by NamPNQ** [comment]
I suggest post sha when create task, and not set sha default when create app

**Comment by NamPNQ** [comment]
You can see: https://github.com/zendesk/samson
Always add you sha before deploy, it's important

**Comment by dcramer** [comment]
The problem with changing the sha after you deploy is that any check you were doing is no longer valid (as the repository can change from the time you initiate the deploy to the time it actually executes). Because of that, and to ensure strong consistency, we set the sha (from the ref) when you create the task.

**Comment by dcramer** [comment]
Actually I think there's some confusion here. The change in bin/run-task seems invalid (we dont want to checkout the ref, we want the actual sha), but I'm not entirely sure about the other change.

It seems like you're describing what I'm suggesting is intended, are you seeing other behavior?

**Pull request closed without merging**
