### PR TITLE
ref: use capture=True when cloning repos

### PR DESCRIPTION
**Pull request by joshuarli**
Trying to get Freight working with seer. Currently, it's stuck cloning the repo, but the sentry issue doesn't provide enough detail. I'd like to see what ssh is spewing on stdout/err.

https://sentry.io/organizations/sentry/issues/3056158590/?project=37617&query=is%3Aunresolved

### CODE REVIEW

**Comment by joshuarli** [comment]
lol ```ImportError while loading conftest '/home/travis/build/getsentry/freight/conftest.py'.
conftest.py:10: in <module>
    from freight.config import create_app, db
freight/config.py:1: in <module>
    import flask
../../../virtualenv/python3.8.13/lib/python3.8/site-packages/flask/__init__.py:19: in <module>
    from jinja2 import Markup, escape
E   ImportError: cannot import name 'Markup' from 'jinja2' (/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/jinja2/__init__.py)```

**Comment by joshuarli** [comment]
ok now it's ```../../../virtualenv/python3.8.13/lib/python3.8/site-packages/flask/json/__init__.py:21: in <module>
    from itsdangerous import json as _json
E   ImportError: cannot import name 'json' from 'itsdangerous' (/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/itsdangerous/__init__.py)```

**Review by dbennett-sentry — APPROVED** [review]

**Comment by mwarkentin** [comment]
What's seer?

**Comment by joshuarli** [comment]
> Details

Refer to the readme in `seer` in `ops`.

**Comment by joshuarli** [comment]
Ugh, Freight is getting so crusty. Gonna freshen it up when I go into the office tomorrow.

**Pull request merged**
