### PR TITLE
Use rev-parse instead of describe to get sha from reference

### PR DESCRIPTION
**Pull request by jkimbo**

### CODE REVIEW

**Comment by jkimbo** [comment]
@thoas I've added a test to make sure it will work when using a sha. Are there any other use cases that I've missed?

**Comment by dcramer** [comment]
this lgtm -- the only other case is a branch which may already be tested implicitly (and i confirmed works)

**Comment by jkimbo** [comment]
Thanks!

**Comment by thoas** [comment]
Great work :+1:

**Pull request merged**
