### PR TITLE
ref(ui): replace moment with date-fns

### PR DESCRIPTION
**Pull request by scttcper**
Replacing moment with date-fns reduces vendor bundle size by about .4 mb

before:
image

after:
image

### CODE REVIEW

**Comment by billyvg** [comment]
@scttcper How does date fns handle different locales? IIRC, last time I looked the support wasn't quite there yet, but that was awhile ago.

**Comment by billyvg** [comment]
Oh, this is freight

**Comment by rhcarvalho** [comment]
> How does date fns handle different locales? IIRC, last time I looked the support wasn't quite there yet, but that was awhile ago.

I don't know if `moment.js` was bug-free, but I'm hitting https://github.com/date-fns/date-fns/issues/1869 when I look at deployment logs (in Safari).

**Comment by rhcarvalho** [comment]
Looks like https://github.com/date-fns/date-fns/blob/master/src/format/index.js could handle the local timezone thing without us doing extra work on our side.

I don't have a devenv to test it, @scttcper @billyvg do you have a way to try this patch?

```diff
diff --git a/static/components/TaskDetails.jsx b/static/components/TaskDetails.jsx
index 4791312..e8b865b 100644
--- a/static/components/TaskDetails.jsx
+++ b/static/components/TaskDetails.jsx
@@ -220,17 +220,13 @@ const TaskDetails = createReactClass({
 
         /***********************************************************************
         This creates an eventlistener for each time element.
-        Fine for current average log size(8-15-17), but memory usuage will spike
+        Fine for current average log size(8-15-17), but memory usage will spike
         for really big logs.
         ***********************************************************************/
         this.highLightDiv(time);
 
-        const timer = new Date(logDataResults.timeStamp[j]);
-        const timeMil = timer.getTime();
-        //Multiple by 60000 to convert offset to milliseconds
-        const offset = timer.getTimezoneOffset() * 60000;
-        const timezone = timeMil - offset;
-        const newDate = new Date(timezone);
+        const timestamp = new Date(logDataResults.timeStamp[j]);
+        time.innerHTML = format(timestamp, 'h:mm:ss aa');
 
         div.innerHTML = ansi_up.ansi_to_html(
           linkifyUrls(lineItem[j][k], {
@@ -240,7 +236,6 @@ const TaskDetails = createReactClass({
             },
           })
         );
-        time.innerHTML = format(newDate, 'h:mm:ss aa');
 
         div.appendChild(time);
         frag.appendChild(div);
```

**Pull request merged**
